export const DEFAULT_DECK = [
  { id: '001', name: '용맹한 기사', cost: 1, atk: 1, hp: 2, ability: '등장: 내 다른 카드 한 장에 공격력을 1 부여합니다.', tag: '등장' },
  { id: '002', name: '멍멍이', cost: 1, atk: 1, hp: 3, ability: '능력 없음', tag: '능력 없음' },
  { id: '003', name: '유령', cost: 4, atk: 0, hp: 1, ability: '이 카드는 처치되지 않습니다.', tag: '패시브' },
  { id: '004', name: '강령술사', cost: 4, atk: 43, hp: 4, ability: '등장: 부활', tag: '등장' },
  { id: '005', name: '바람 마법사', cost: 3, atk: 3, hp: 4, ability: '등장: 바운스', tag: '등장' },
  { id: '006', name: '도적단', cost: 2, atk: 2, hp: 2, ability: '등장: 훔치기', tag: '등장' },
  { id: '007', name: '겁쟁이 기사', cost: 2, atk: 1, hp: 3, ability: '등장: 공격력+1', tag: '등장' },
  { id: '008', name: '7번 드래곤', cost: 7, atk: 7, hp: 7, ability: '능력 없음', tag: '능력 없음' },
  { id: '009', name: '6번 드래곤', cost: 6, atk: 6, hp: 6, ability: '능력 없음', tag: '능력 없음' },
  { id: '010', name: '5번 드래곤', cost: 5, atk: 5, hp: 5, ability: '능력 없음', tag: '능력 없음' },
  { id: '011', name: '4번 드래곤', cost: 4, atk: 4, hp: 4, ability: '능력 없음', tag: '능력 없음' },
  { id: '012', name: '3번 드래곤', cost: 3, atk: 33, hp: 33, ability: '능력 없음', tag: '능력 없음' },
  { id: '013', name: '2번 드래곤', cost: 2, atk: 2, hp: 2, ability: '능력 없음', tag: '능력 없음' },
  { id: '014', name: '1번 드래곤', cost: 1, atk: 1, hp: 1, ability: '능력 없음', tag: '능력 없음' },
  { id: '015', name: '음악인', cost: 7, atk: 4, hp: 6, ability: '등장: 비용 감소', tag: '등장' },
  { id: '016', name: '화난 사람', cost: 1, atk: 1, hp: 1, ability: '능력 없음', tag: '능력 없음' },
  { id: '017', name: '이만진', cost: 2, atk: 2, hp: 2, ability: '능력 없음', tag: '능력 없음' },
  { id: '018', name: '삼만진', cost: 3, atk: 3, hp: 3, ability: '능력 없음', tag: '능력 없음' },
  { id: '019', name: '사만진', cost: 1, atk: 1, hp: 3, ability: '능력 없음', tag: '능력 없음' },
  { id: '020', name: '도적단 두목', cost: 2, atk: 2, hp: 2, ability: '등장: 훔치기', tag: '등장' },
];

export const INITIAL_LAYOUT_COORDS = {
  "costTop": 7,
  "costLeft": 10,
  "costSize": 10,
  "nameTop": 4,
  "nameLeft": 25,
  "nameSize": 10,
  "abilityTop": 68,
  "abilityLeft": 8,
  "abilitySize": 7,
  "abilityWidth": 85,
  "abilityHeight": 60,
  "atkTop": 53,
  "atkLeft": 25,
  "atkSize": 15,
  "hpTop": 53,
  "hpLeft": 73,
  "hpSize": 15,
  "bgColor": "#35363b",
  "uiBarColor": "#5a5d68"
};